<a href="https://colab.research.google.com/github/Amoasi08/Amoasi08/blob/main/SeabornCar_crushes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
#Load the car crashes dataset
#Show a sample of the dataset
car = sns.load_dataset('car_crashes')
car.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

**Understanding the Data**

car.shape \
car.dtypes \
car.info \
car.describe

In [3]:
car.shape

(51, 8)

In [4]:
car.dtypes

total             float64
speeding          float64
alcohol           float64
not_distracted    float64
no_previous       float64
ins_premium       float64
ins_losses        float64
abbrev             object
dtype: object

In [5]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   total           51 non-null     float64
 1   speeding        51 non-null     float64
 2   alcohol         51 non-null     float64
 3   not_distracted  51 non-null     float64
 4   no_previous     51 non-null     float64
 5   ins_premium     51 non-null     float64
 6   ins_losses      51 non-null     float64
 7   abbrev          51 non-null     object
dtypes: float64(7), object(1)
memory usage: 3.3+ KB

In [6]:
car.describe()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,15.790196,4.998196,4.886784,13.573176,14.004882,886.957647,134.493137
std,4.122002,2.017747,1.729133,4.508977,3.764672,178.296285,24.835922
min,5.900000,1.792000,1.593000,1.760000,5.900000,641.960000,82.750000
25%,12.750000,3.766500,3.894000,10.478000,11.348000,768.430000,114.645000
50%,15.600000,4.608000,4.554000,13.857000,13.775000,858.970000,136.050000
75%,18.500000,6.439000,5.604000,16.140000,16.755000,1007.945000,151.870000
max,23.900000,9.450000,10.038000,23.661000,21.280000,1301.520000,194.780000

**Data Exploration**

In [7]:
highest_total_row = car.loc[car['total'].idxmax()]
print(highest_total_row)

total               23.9
speeding           5.497
alcohol           10.038
not_distracted    23.661
no_previous       20.554
ins_premium       688.75
ins_losses        109.72
abbrev                ND
Name: 34, dtype: object

In [8]:
lowest_total_row = car.loc[car['total'].idxmin()]
print(lowest_total_row)

total                 5.9
speeding            2.006
alcohol             1.593
not_distracted        5.9
no_previous           5.9
ins_premium       1273.89
ins_losses         136.05
abbrev                 DC
Name: 8, dtype: object

In [9]:
#Highest State
lowest_total = car['total'].min()
state_with_lowest_total = car.loc[car['total'].idxmin(), 'abbrev']
print(f"{state_with_lowest_total} has the lowest total car crashes with {lowest_total} crashes")

#Lowest State
highest_total = car['total'].max()
state_with_highest_total = car.loc[car['total'].idxmax(), 'abbrev']
print(f"{state_with_highest_total} has the highest total car crashes with {highest_total} crashes")

DC has the lowest total car crashes with 5.9 crashes
ND has the highest total car crashes with 23.9 crashes

In [31]:
#Another way to get the Highest and the Lowest State

#Highest State
#1. Sort the total in descending order
sort_descending_total = car.sort_values(by='total', ascending=False).head(1)

#2. Get the first row
highest_total_row = sort_descending_total.iloc[0]
highest_total_row[["abbrev", "total"]]
print(f"{highest_total_row['abbrev']} has the highest total car crashes with {highest_total_row['total']} crashes")

SC has the highest total car crashes with 23.9 crashes

In [32]:
#Lowest State
#1. Sort the total in ascending order
sort_ascending_total = car.sort_values(by='total', ascending=True).head(1)

#2. Get the first row
lowest_total_row = sort_ascending_total.iloc[0]
print(f"{lowest_total_row['abbrev']} has the lowest total car crashes with {lowest_total_row['total']} crashes")

DC has the lowest total car crashes with 5.9 crashes

In [10]:
#Correlation
speed_corr = car['speeding'].corr(car['total'])
print("Correlation between 'speeding' and 'total':", speed_corr)

alcohol_corr = car['alcohol'].corr(car['total'])
print("Correlation between 'alcohol' and 'total':", alcohol_corr)

Correlation between 'speeding' and 'total': 0.6115476008001183
Correlation between 'alcohol' and 'total': 0.8526132163334914

In [13]:
#Top 10 states with insurance premium
# Sort by insurance premiums in descending order
top_10_premiums = car.sort_values(by="ins_premium", ascending=False).head(10)

# Display the result
print(top_10_premiums[["abbrev", "ins_premium"]])

   abbrev  ins_premium
30     NJ      1301.52
18     LA      1281.55
8      DC      1273.89
32     NY      1234.31
9      FL      1160.13
39     RI      1148.99
7      DE      1137.87
22     MI      1110.61
6      CT      1068.73
1      AK      1053.48

5.9